#!/usr/bin/env bash

case "$1" in
    "")
        echo Rarameter missing
        exit 1;;
    "install")
        mkdir cert
        wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64 -O cert/mkcert
        chmod +x cert/mkcert
        cert/mkcert -install
        (cd cert; ./mkcert localhost)
        (cd cert; cat localhost-key.pem localhost.pem | openssl pkcs12 -export -out cert.p12)
        (cd cert; keytool -importkeystore -srckeystore cert.p12 -srcstoretype pkcs12 -destkeystore cert.jks)
        echo "Instalation complete";;
    "nodejs")
        echo Running nodejs backend
        nodejs backend/nodejs/hello.js;;
    "java")
        echo Running java backend
        java -jar backend/java/hello/target/hello-1.0-SNAPSHOT-jar-with-dependencies.jar;;
    *)
        echo Rarapeters not recognized
        exit 1;;
esac

